//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDigit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameLaw { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string TaxNo { get; set; }
        public string Bulstat { get; set; }
        public string MOLName { get; set; }
        public string ReceiverName { get; set; }
        public string Licence { get; set; }
        public string DrugLicence { get; set; }
        public string ShipmentAddress { get; set; }
        public string Email { get; set; }
        public int InvoiceReceiveTypeID { get; set; }
        public int AppUserID { get; set; }
        public int CustomerGroupID { get; set; }
        public int PostCodeID { get; set; }
        public int AreaCodeID { get; set; }
        public string RZOKCode { get; set; }
        public int DaysDelayPayFree { get; set; }
        public int DaysDelayPayNZOK { get; set; }
        public decimal ArticleBGDiscountPercent { get; set; }
        public decimal ArticleForeignDiscountPercent { get; set; }
        public decimal ArticleNZOKDiscountPercent { get; set; }
        public decimal MaxCredit { get; set; }
        public decimal FixedProfitPercent { get; set; }
        public decimal FixedOverratePercent { get; set; }
        public decimal OverrateDecreasePercent { get; set; }
        public int PaymentTypeID { get; set; }
        public int PaymentTypeIDNZOK { get; set; }
        public int PreferedDiscountTypeID { get; set; }
        public int PreferedDiscountTypeIDNZOK { get; set; }
        public int SaleDiscountTypeID { get; set; }
        public string Remark { get; set; }
        public bool isActive { get; set; }
        public bool isDiscountException { get; set; }
        public bool isSaleOrderAllowed { get; set; }
        public bool isDeleteAllowed { get; set; }
        public bool isVATRegistered { get; set; }
        public bool isDiscountInPrice { get; set; }
        public bool isPreferedFinanceRebate { get; set; }
        public bool isMathDiscountType { get; set; }
        public bool isClient { get; set; }
        public Nullable<int> PharmacyConsultantID { get; set; }
        public Nullable<decimal> StockCredit { get; set; }
        public Nullable<int> SoftwareID { get; set; }
        public Nullable<bool> LibraEvent { get; set; }
        public Nullable<decimal> PartnerCapital { get; set; }
        public Nullable<System.DateTime> PartnerEndDate { get; set; }
        public Nullable<System.DateTime> PartnerStartDate { get; set; }
        public bool isPricing { get; set; }
        public Nullable<short> ContractType { get; set; }
        public Nullable<decimal> ContractSum { get; set; }
        public Nullable<decimal> BonusOborotPercent { get; set; }
        public Nullable<decimal> BonusOborot { get; set; }
        public Nullable<bool> isPriceWithoutRounding { get; set; }
        public string BankCountryCode { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string IBAN { get; set; }
        public Nullable<int> SoftwareConsultantID { get; set; }
        public string Status { get; set; }
        public Nullable<bool> isPrintDelayPayments { get; set; }
        public bool isRabatDenied { get; set; }
        public decimal BonusOborotPercent2 { get; set; }
        public Nullable<bool> isActionActavis { get; set; }
        public Nullable<System.DateTime> AuctionStartDate { get; set; }
        public Nullable<System.DateTime> AuctionEndDate { get; set; }
        public Nullable<int> AppUserID2 { get; set; }
        public Nullable<decimal> ContractInternetPercent { get; set; }
        public Nullable<decimal> ContractInternetSum { get; set; }
        public Nullable<decimal> ContractMonthlyTax { get; set; }
        public Nullable<bool> isPricingNZOK { get; set; }
        public Nullable<short> RetailerPriceCalcTypeID { get; set; }
        public Nullable<short> RetailerPriceCalcTypeIDNZOK { get; set; }
        public Nullable<bool> ShowWarningLabel { get; set; }
        public Nullable<bool> isDiscountInPriceNZOK { get; set; }
        public Nullable<int> MerchandiserID { get; set; }
        public Nullable<bool> isActionDenied { get; set; }
        public Nullable<bool> isSpecialOrder { get; set; }
        public Nullable<int> NationalCustomerGroupID { get; set; }
        public Nullable<short> PostCode { get; set; }
        public Nullable<bool> isProtocol5Allowed { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> ContractInstallationDate { get; set; }
        public Nullable<short> IMSGroup { get; set; }
        public Nullable<int> CustomerDeliveryGroup { get; set; }
        public Nullable<bool> isJoinInMyPharmacy { get; set; }
        public Nullable<bool> isJoinInAdvertisingShopWindows { get; set; }
        public Nullable<int> IMSCodeID { get; set; }
        public Nullable<bool> isNZOKHalfMargin { get; set; }
        public Nullable<decimal> FixedProfitPercentNZOK { get; set; }
        public Nullable<int> SaleDiscountTypeIDNZOK { get; set; }
        public string CodeLocation { get; set; }
        public Nullable<bool> isNZOKDelayedAllowed { get; set; }
        public Nullable<int> NZOKDelayedDays { get; set; }
        public Nullable<System.DateTime> StartBonus { get; set; }
        public Nullable<System.DateTime> EndBonus { get; set; }
        public Nullable<int> CollateralTypeID { get; set; }
        public Nullable<decimal> CollateralSum { get; set; }
        public Nullable<long> SAPNumber { get; set; }
        public Nullable<bool> isJoinOrderDenied { get; set; }
        public Nullable<int> MaxDeliveryDays { get; set; }
        public Nullable<bool> isPharmacyMaxNZOKPrice { get; set; }
        public Nullable<bool> XMLElectronicInvoice { get; set; }
        public Nullable<bool> IndividualConditions { get; set; }
        public Nullable<int> ContractCustomerID { get; set; }
        public string EFakturaEmail { get; set; }
        public Nullable<System.DateTime> XMLEIStartDate { get; set; }
        public Nullable<short> SendPricelist { get; set; }
        public string SendPricelistEmail { get; set; }
        public Nullable<bool> isPrintDurability { get; set; }
        public Nullable<byte> NumMonths { get; set; }
        public Nullable<int> suspensionDays { get; set; }
        public Nullable<int> ContractPaymentDays { get; set; }
        public Nullable<int> ContractInvoicedMonths { get; set; }
        public string Category { get; set; }
        public string Segment { get; set; }
        public Nullable<decimal> Potential { get; set; }
        public Nullable<byte> RiskClass { get; set; }
        public Nullable<bool> StateOwned { get; set; }
        public Nullable<byte> PaymentClassification { get; set; }
        public Nullable<int> ClassPaymentDays { get; set; }
        public Nullable<decimal> ClassMaxCreditLimit { get; set; }
        public Nullable<int> AvgPaymentDays { get; set; }
        public Nullable<int> RoyaltyCode { get; set; }
        public Nullable<bool> ExcludeHighCostFromLimit { get; set; }
        public Nullable<decimal> OverratePercent { get; set; }
        public Nullable<bool> isWithoutInternetProhibition { get; set; }
        public Nullable<bool> Watchlist { get; set; }
        public Nullable<bool> isGrayList { get; set; }
        public Nullable<System.DateTime> GrayListEntryDate { get; set; }
        public Nullable<bool> isBlackList { get; set; }
        public Nullable<bool> isBlackListActive { get; set; }
        public Nullable<System.DateTime> BlackListEntryDate { get; set; }
        public string ExtraEmail { get; set; }
        public string ServiceCategory { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<decimal> CalcPotential { get; set; }
        public Nullable<decimal> AvgNetoVATL12 { get; set; }
        public Nullable<int> AvgPaymentTerms { get; set; }
        public Nullable<decimal> LoanLeftByGroup { get; set; }
        public Nullable<decimal> CalcMaxCredit { get; set; }
        public string OldName { get; set; }
        public Nullable<bool> isPharmacyMAXFreePrice { get; set; }
        public Nullable<bool> isBetty { get; set; }
        public Nullable<bool> isPharmacyZeroRebatePrice { get; set; }
        public Nullable<decimal> MaxCreditK1 { get; set; }
    }
}
